### PR TITLE
Mountain array

### PR DESCRIPTION
**Pull request by podmar**
completed the mountain array challenge & updated readme

### CODE REVIEW

**Review by 0sc — CHANGES_REQUESTED** [review]
Almost there 👏 

It's missing a few edge cases: 
1. A mountain must have `arr.length >= 3`
i.e. If you test it with `Example 1` in the description it should return false

2. Peak must be within the array. i.e. it should have some elements in ascending order before it and some in descending order after it. So if `i` is peak index, then there must exist some
`arr[0] < arr[1] < ... arr[i] > arr[i+1] ... > arr[arr.length-1]`
i.e. if you test with [0, 1, 2, 3, 4, 5] it should return `False`

**Comment by podmar** [comment]
Hi Oscar! 🙏🏻 thank you for the feedback! Should I close the PR and start a new one, or make new commits and continue with the existing pr?

**Comment by 0sc** [comment]
> Hi Oscar! 🙏🏻 thank you for the feedback! Should I close the PR and start a new one, or make new commits and continue with the existing pr?

You can continue with this one.

**Comment by podmar** [comment]
Hi Oscar, I added one more condition, checked on leetcode and merged. 💪🏻

**Pull request merged**
